server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8080

spring:
  profiles:
    default: local

  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd'T'HH:mm:ss
    # swagger 3.0 관련
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql: trace