spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:simple-riple
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true